export const GO = {
    SUSCRIBE: 'suscribe',
    CONFIRM: 'confirm',
    LOGIN: 'login',
    HOME: 'home',
    BULK_TRUNK: 'bulkTrunk',
    IMPACT_ENTRY: 'impactEntry',
    SEARCH:'search',
    BASKET:'basket',
    TREE_EMPTY: 'emptyTree',
    TREE: 'tree',
    ROOT: 'root',
    COMPARE_EMPTY: 'compareEmpty',
    COMPARE_PARTIAL: 'comparePartial',
    COMPARE: 'compare',
}