export const GO = {
    DATA_EXPLAINED: "datasExplained",
    ROAD_MAP: "roadMap",
    SUSCRIBE: 'suscribe',
    CONFIRM: 'confirm',
    LOGIN: 'login',
    PLAN_INTRO: 'planIntro',
    PLAN: 'plan',
    IMPACT_ENTRY: 'impactEntry',
    ADD_IMPACT_ENTRY: 'addImpactEntry',
    ADD_FACET_ENTRY: 'addFacetEntry',
    ADD_RESSOURCE: 'addRessource',
    SEARCH: 'search',
    BASKET: 'basket',
    TREE_EMPTY: 'emptyTree',
    TREE: 'tree',
    EQUIV: 'equiv',
    CREATE_TREE: 'createTree',
    ROOT: 'root',
    TEAM: 'team',
    MESSAGE: 'message',
    COMPARE_EMPTY: 'compareEmpty',
    COMPARE_PARTIAL: 'comparePartial',
    COMPARE: 'compare',
}