export const GO = {
    BASKET:'basket',
    BULK_TRUNK: 'bulkTrunk',
    CONFIRM: 'confirm',
    COMPARE_EMPTY: 'compareEmpty',
    COMPARE_PARTIAL: 'comparePartial',
    COMPARE: 'compare',
    HOME: 'home',
    IMPACT_ENTRY: 'impactEntry',
    LOGIN: 'login',
    PLAN: 'plan',
    SEARCH:'search',
    TREE_EMPTY: 'emptyTree',
    TREE: 'tree',
    ROOT: 'root',
    SUSCRIBE: 'suscribe',
}