export default {
    ADD_BRANCHES:'addBranches',
    ADD_FACET: "addFacet",
    ADD_IMPACT: "addImpact",
    ADD_ROOTS:'addRoots',
    ADD_FACETS: 'addFacets',
    ADD_IMPACTS: 'addImpacts',
    ADD_IMPACTS_TANK: 'addImpactsTank',
    ADD_TO_BASKET: 'addToBasket',
    CLEAR_DIALOG_DATA: 'clearDialogData',
    CLEAR_RESULTS: 'clearResults',
    CLEAR_SEARCH: 'clearSearch',
    DELETE_FACETS: 'deleteFacets',
    DELETE_IMPACTS: 'deleteImpacts',
    DELETE_ROOT: 'deleteRoot',
    DELETE_BRANCH: 'deleteBranch',
    HIDE_FACET_DIALOG:'hideFacetDialog',
    HIDE_IMPACT_DIALOG:'hideImpactDialog',
    RENAME_TRUNK: 'renameTree',
    REMOVE_FROM_BASKET:'removeFromBasket',
    SET_ROOTS:'setRoots',
    SET_BRANCHES:'setBranches',
    SET_TANK: 'setTank',
    SET_TRUNK: 'setTrunk',
    SHOW_DIALOG: "showDialog",
    SHOW_FACET_ENTRY_DIALOG: "showFacetEntryDialog",
    SHOW_IMPACT_ENTRY_DIALOG: "showImpactEntryDialog",
    SHOW_OTHER_TREE_DIALOG: "showOtherTreeDialog",
    SWAP_LEFT_RIGHT: 'swapLeftRight',
    INIT_COMPARE_TO: 'initCompareTo',
    UPDATE_DIALOG_VISIBILITY: 'updateDialogVisibility',
    UPDATE_DIALOG_DATA: 'updateDialogData',
    PUT_TRUNK_QUANTITY: 'upsertQuantity'
};