export default {
    ADD_FACET: "addFacet",
    ADD_SEED: 'addSeed',
    CLEAR_DIALOG_DATA: 'clearDialogData',
    CLEAR_RESULTS: 'clearResults',
    CLEAR_SEARCH: 'clearSearch',
    CLEAR_COMPARE_TO: 'clearCompareTo',
    CLOSE_TREE: 'closeTree',
    DELETE_FACETS: 'deleteFacets',
    DELETE_ROOT: 'deleteRoot',
    HIDE_FACET_DIALOG:'hideFacetDialog',
    RENAME_TREE: 'renameTree',
    SHOW_DIALOG: "showDialog",
    SHOW_FACET_ENTRY_DIALOG: "showFacetEntryDialog",
    SHOW_OTHER_TREE_DIALOG: "showOtherTreeDialog",
    SWAP_LEFT_RIGHT: 'swapLeftRight',
    OPEN_TREE: 'openTree',
    OPEN_COMPARE_TO: 'openCompareTo',
    UPDATE_ADDING_SEED: 'updateAddingSeed',
    UPDATE_DIALOG_VISIBILITY: 'updateDialogVisibility',
    UPDATE_DIALOG_DATA: 'updateDialogData',
    UPDATE_GRANDEURS: "UPDATE_GRANDEURS",
    UPSERT_QUANTITY: 'upsertQuantity'
};