export default {
    ADD_FACET: "addFacet",
    ADD_ROOTS: 'addRoots',
    ADD_RESSOURCE_TO: 'addRessourceTo',
    CLONE_TREE:"cloneTree",
    CLONE_OPEN_TREE:"cloneOpenTree",
    CREATE_AND_OPEN_TREE: 'onCreateAndOpenTree',
    CREATE_ADD_RESSOURCE: 'createAddRessource',
    CREATE_FACET_ENTRY: 'onCreateFacetEntry',
    CREATE_TRUNK_THEN_SEED: 'onCreateTrunkThenSeed',
    CREATE_TREE: 'onCreateTree',
    DELETE_FACETS: 'deleteFacets',
    DELETE_TREE: 'deleteTree',
    DELETE_ROOT: 'deleteRessources',
    EXCEPTION: 'exception',
    LOAD_FACETS: 'loadFacets',
    LOAD_UNITS: 'loadUnits',
    LOAD_OPEN_TREE: 'loadOpenTree',
    LOAD_TRUNK: 'loadTrunk',
    LOAD_ROOTS: 'loadRoots',
    MOUNT_APP: 'mountApp',
    LOAD_OPEN_COMPARE_TO: 'loadOpenCompareTo',
    POPULATE_ROOTS: "populateRoots",
    RENAME_TRUNK: 'renameTrunk',
    SEARCH_TREE: 'searchTree',
    SEARCH_FACET_ENTRY: 'searchFacetEntry',
    UPSERT_QUANTITY: "upsertQuantity"
};