export default {
    ADD_FACET: "addFacet",
    CLONE_TREE:"cloneTree",
    CLONE_OPEN_TREE:"cloneOpenTree",
    CREATE_AND_OPEN_TREE: 'onCreateAndOpenTree',
    CREATE_ADD_RESSOURCE: 'createAddRessource',
    ADD_RESSOURCE: 'addRessource',
    ADD_RESSOURCE_TO: 'addRessourceTo',
    CREATE_SEED: 'onCreateSeed',
    CREATE_FACET_ENTRY: 'onCreateFacetEntry',
    CREATE_TRUNK_THEN_SEED: 'onCreateTrunkThenSeed',
    CREATE_TRUNK: 'onCreateTrunk',
    DELETE_FACETS: 'deleteFacets',
    DELETE_TREE: 'deleteTree',
    DELETE_ROOT: 'deleteRessources',
    EXCEPTION: 'exception',
    FOCUS_ON_SEARCH: "focusOnSearch",
    LOAD_UNITS: 'loadUnits',
    LOAD_OPEN_TREE: 'loadOpenTree',
    LOAD_TREE: 'loadTree',
    MOUNT_APP: 'mountApp',
    LOAD_OPEN_COMPARE_TO: 'loadOpenCompareTo',
    RENAME_TREE: 'renameTree',
    SEARCH: 'onSearch',
    SEARCH_FACET_ENTRY: 'searchFacetEntry',
    UPSERT_QUANTITY: "upsertQuantity"
};