const Event = {
    TRUNK_HEADER_SELECTED : 'TRUNK_HEADER_SELECTED',
    TREE_CHANGED : 'TREE_CHANGED',
    TRUNK_CREATED : 'TRUNK_CREATED',
    TREE_SELECTED : 'TREE_SELECTED',
    TREE_UNSELECTED : 'TREE_UNSELECTED',
    TREE_DELETED : 'TREE_DELETED',
    TREE_ALL_DELETED : "TREE_ALL_DELETED"
};

export default Event