export const On = {
    ADD_FACET: "addFacet",
    CLEAR_LINK_EDIT: "onClearLinkEdit",
    CREATE_AND_OPEN_TREE: 'onCreateAndOpenTree',
    CREATE_SEED: 'onCreateSeed',
    CREATE_TRUNK_THEN_SEED: 'onCreateTrunkThenSeed',
    CREATE_TRUNK: 'onCreateTrunk',
    LINK_CHANGED: 'onLinkChanged',
    OPEN_TREE: 'onOpenTree',
    UPDATE_ADDING_SEED_CLICK: 'onUpdateAddingSeedClick',
    UPDATE_SEARCH_TERM: "updateSearchTerm",
    PATH_CHANGED: "onPathChanged",
    PATH_CLICK: 'onPathClick',
    PATH_LINK_CLICK: 'onPathLinkClick',
    REFRESH_ROOT: "onRefreshRoot",
    ROOT_CLICK: 'onRootClick',
    SEARCH: 'onSearch',
    UPSERT_LINK: "upsertLink"
};

export const Do = {
    ADD_FACET: "addFacet",
    ADD_TO_PATH: 'addToPath',
    ADD_SEED: 'addSeed',
    CHANGE_PATH_INDEX: 'changePathIndex',
    CLEAR_RESULTS: 'clearResults',
    CLEAR_SEARCH: 'clearSearch',
    CLEAR_CREATE_DIALOG_DATA: 'clearCreateDialogData',
    CLOSE_TREE: 'closeTree',
    CLOSE_CREATE_DIALOG: 'closeCreateDialog',
    OPEN_CREATE_DIALOG: "openCreateDialog",
    OPEN_TREE: 'openTree',
    SET_CREATE_DIALOG_DATA: 'setCreateDialogData',
    UPDATE_ADDING_SEED: 'updateAddingSeed',
    UPDATE_CREATE_DIALOG: 'updateCreateDialog',
    UPDATE: 'update',
    UPDATE_LINK_EDIT: 'updateLinkEdit',
    UPDATE_ROOT: 'updateRoot',
    UPDATE_PATH_ITEM: 'updatePathItem',
    UPDATE_QT: 'updateQt',
    UPDATE_RESULTS: 'updateResults',
    UPDATE_SEARCHING: 'updateSearching',
    UPDATE_TERM: 'updateTerm',
};