export const On = {
    ADD_FACET: "addFacet",
    CLEAR_LINK_EDIT: "onClearLinkEdit",
    CREATE_AND_OPEN_TREE: 'onCreateAndOpenTree',
    CREATE_SEED: 'onCreateSeed',
    CREATE_TRUNK_THEN_SEED: 'onCreateTrunkThenSeed',
    CREATE_TRUNK: 'onCreateTrunk',
    LINK_CHANGED: 'onLinkChanged',
    LOAD_UNITS: 'loadUnits',
    MOUNT_APP: 'mountApp',
    OPEN_TREE: 'onOpenTree',
    UPDATE_ADDING_SEED_CLICK: 'onUpdateAddingSeedClick',
    UPDATE_SEARCH_TERM: "updateSearchTerm",
    PATH_CHANGED: "onPathChanged",
    PATH_CLICK: 'onPathClick',
    PATH_LINK_CLICK: 'onPathLinkClick',
    REFRESH_ROOT: "onRefreshRoot",
    ROOT_CLICK: 'onRootClick',
    SEARCH: 'onSearch',
    UPSERT_LINK: "upsertLink"
};

export const Do = {
    ADD_FACET: "addFacet",
    ADD_TO_PATH: 'addToPath',
    ADD_SEED: 'addSeed',
    CHANGE_PATH_INDEX: 'changePathIndex',
    CLEAR_RESULTS: 'clearResults',
    CLEAR_SEARCH: 'clearSearch',
    CLOSE_TREE: 'closeTree',
    HIDE_TRUNK_DIALOG:'hideTrunkDialog',
    HIDE_FACET_DIALOG:'hideFacetDialog',
    LOAD_UNITS: 'loadUnits',
    SHOW_TRUNK_DIALOG: "showTrunkDialog",
    SHOW_FACET_DIALOG: "showFacetDialog",
    UPDATE_TRUNK_DIALOG_VISIBILITY: "updateTrunkDialogVisibility",
    UPDATE_FACET_DIALOG_VISIBILITY: "updateFacetDialogVisibility",
    OPEN_TREE: 'openTree',
    UPDATE_ADDING_SEED: 'updateAddingSeed',
    UPDATE: 'update',
    UPDATE_TRUNK_DIALOG_DATA: 'updateTrunkDialogData',
    UPDATE_FACET_DIALOG_DATA: 'updateFacetDialogData',
    UPDATE_LINK_EDIT: 'updateLinkEdit',
    UPDATE_ROOT: 'updateRoot',
    UPDATE_PATH_ITEM: 'updatePathItem',
    UPDATE_QT: 'updateQt',
    UPDATE_RESULTS: 'updateResults',
    UPDATE_SEARCHING: 'updateSearching',
    UPDATE_TERM: 'updateTerm',
};

export const Dial = {
    TRUNK : "trunk",
    FACET: "facet"
};